### ISSUE TITLE
プロキシ設定

### ISSUE THREAD

**Issue by wtnb75** [wtnb75/selenible#15]
- ブラウザによって異なる
- とりあえずPhantomJSではconfigで設定できる状態にしてあるが…
- 同じ書き方で設定したい

**Comment by wtnb75** [comment]
イメージ

```yaml
- name: proxy setting
  proxy:
    http: http://user:password@proxy.local:8080/
    https: http://user:password@proxy.local:8080/
    no: [localhost, .google.com]
```

環境変数からもらうことが多いのかも。

```yaml
- name: proxy setting
  proxy:
    http: "{{env.http_proxy}}"
    https: "{{env.https_proxy}}"
    no: "{{env.no_proxy}}"
```

```yaml
- name: proxy setting
  proxy: auto
```
